import { verifyUserInfo } from "../hack_core/fetch_pdd_user_info";

const cookie =
  "// Semicolon separated Cookie File\n" +
  "// This file was generated by EditThisCookie\n" +
  "// Details: http://www.ietf.org/rfc/rfc2109.txt\n" +
  "// Example: http://www.tutorialspoint.com/javascript/javascript_cookies.htm\n" +
  "_a42=6fbd982d-1e76-434d-a1af-4f864275d15a;_bee=IyctlSCGL1k8SVLI2bTMNCIh9EpeZLCr;_crr=IyctlSCGL1k8SVLI2bTMNCIh9EpeZLCr;_f77=49d2f578-23b2-439b-aa4e-a84f95cff979;api_uid=rBQdO2COIhEqVT6MIio9Ag==;rcgk=IyctlSCGL1k8SVLI2bTMNCIh9EpeZLCr;rckk=IyctlSCGL1k8SVLI2bTMNCIh9EpeZLCr;ru1k=49d2f578-23b2-439b-aa4e-a84f95cff979;ru2k=6fbd982d-1e76-434d-a1af-4f864275d15a;_nano_fp=XpEalpCjlpEYXqdjn9_bn7ZFBW6yuyeLtaXMCztW;csrfToken=tcc96QnwbdKeqYlJSzqJQn10;SUB_PASS_ID=eyJ0Ijoic0FJZHVLOERDNVRsS2xNL1lESU5PV2ErT1pGMlJhY3ArUGVlWmV2Nk9pQTk5Q0dkanYzbEtlaEVQMi9rdDlLNCIsInYiOjEsInMiOjcsIm0iOjUwNjY3Mzk3MCwidSI6OTM5MTc4OTJ9;SUB_SYSTEM_ID=7;";

const cookie_missing_key =
  "_a42=6fbd982d-1e76-434d-a1af-4f864275d15a;_bee=IyctlSCGL1k8SVLI2bTMNCIh9EpeZLCr;_crr=IyctlSCGL1k8SVLI2bTMNCIh9EpeZLCr;_f77=49d2f578-23b2-439b-aa4e-a84f95cff979;api_uid=rBQdO2COIhEqVT6MIio9Ag==;rcgk=IyctlSCGL1k8SVLI2bTMNCIh9EpeZLCr;rckk=IyctlSCGL1k8SVLI2bTMNCIh9EpeZLCr;ru1k=49d2f578-23b2-439b-aa4e-a84f95cff979;ru2k=6fbd982d-1e76-434d-a1af-4f864275d15a;_nano_fp=XpEalpCjlpEYXqdjn9_bn7ZFBW6yuyeLtaXMCztW;csrfToken=tcc96QnwbdKeqYlJSzqJQn10;SUB_PS_ID=eyJ0Ijoic0FJZHVLOERDNVRsS2xNL1lESU5PV2ErT1pGMlJhY3ArUGVlWmV2Nk9pQTk5Q0dkanYzbEtlaEVQMi9rdDlLNCIsInYiOjEsInMiOjcsIm0iOjUwNjY3Mzk3MCwidSI6OTM5MTc4OTJ9;SUB_SYSTEM_ID=7;";
const cookie_wrong_value =
  "_a42=6fbd982d-1e76-434d-a1af-4f864275d15a;_bee=IyctlSCGL1k8SVLI2bTMNCIh9EpeZLCr;_crr=IyctlSCGL1k8SVLI2bTMNCIh9EpeZLCr;_f77=49d2f578-23b2-439b-aa4e-a84f95cff979;api_uid=rBQdO2COIhEqVT6MIio9Ag==;rcgk=IyctlSCGL1k8SVLI2bTMNCIh9EpeZLCr;rckk=IyctlSCGL1k8SVLI2bTMNCIh9EpeZLCr;ru1k=49d2f578-23b2-439b-aa4e-a84f95cff979;ru2k=6fbd982d-1e76-434d-a1af-4f864275d15a;_nano_fp=XpEalpCjlpEYXqdjn9_bn7ZFBW6yuyeLtaXMCztW;csrfToken=tcc96QnwbdKeqYlJSzqJQn10;SUB_PASS_ID=eyJ0IjoiJZHVLOERDNVRsS2xNL1lESU5PV2ErT1pGMlJhY3ArUGVlWmV2Nk9pQTk5Q0dkanYzbEtlaEVQMi9rdDlLNCIsInYiOjEsInMiOjcsIm0iOjUwNjY3Mzk3MCwidSI6OTM5MTc4OTJ9;SUB_SYSTEM_ID=7;";

verifyUserInfo({ username: "乐和食品店:冯露", password: "xx", cookie }).then(e => {
  console.log(e)
})
