usersInfo:
  collName: accounts
  description: 用户信息
  note:
  baseType: 1
  path: /janus/api/new/userinfo
  isAnti: false
  isInc: false
  params:
  pagination:
  ids: id

recentOrders:
  collName: orders
  description: 最近订单
  baseType: 1
  path: /mangkhut/mms/recentOrderList
  isAnti: true
  isInc: true
  params:
    orderType: 0                # 订单状态，默认为 1 （待发货），0 表全选
    afterSaleType: 0            # 售后状态，默认为 1（无售后/取消售后），0 表全选
    remarkStatus: -1            # 标注状态，-1 表全选
    urgeShippingStatus: -1      # 承诺发货时间，-1 表全选
    sortType: 8                 # 排序类型，默认为 7（最新上交订单在上），爬取适合选 8（在下）
    groupStartTime: 1613134083  # 开始时间，中国某日零点，秒级时间戳
    groupEndTime: 1620910083    # 结束时间，中国次日零点，秒级时间戳
    pageNumber: 1
    pageSize: 50
  pagination:
    pageNumKey: pageNumber
    pageSizeKey: pageSize
    totalSizeKey: totalItemNum
    itemsKey: pageItems
  ids: order_sn
  note:

adFangxin:
  collName: ad_fangxin
  description: 放心推单元列表
  baseType: 2
  path: /venus/api/cpa/goods/list
  isAnti: true
  isInc: true
  params:
    mallId: 506673970       # 店铺ID
    scenesType: 6           # 场景（放心推，固定参数）
    startDate: 2021-05-12   # 指定日期，YYYY-MM-DD
    endDate: 2021-05-12     # 指定日期， YYYY-MM-DD
    searchKey: null
    pageNumber: 1
    pageSize: 50
  pagination:
    pageNumKey: pageNumber
    pageSizeKey: pageSize
    totalSizeKey: total
    itemsKey: result
  ids:
    - unitId
    - targetDate
  note:

adSearch:
  collName: ad_search
  description: 多多搜索单元列表
  baseType: 2
  path: /venus/api/unit/listPage
  isAnti: true
  isInc: true
  params:
    mallId: 506673970       # 店铺ID
    scenesType: 0           # 场景（多多搜索，固定参数）
    beginDate: 2021-05-12   # 区别于"放心推"的startDate
    endDate: 2021-05-12     #
    pageNumber: 1
    pageSize: 50
  pagination:
    pageNumKey: pageNumber
    pageSizeKey: pageSize
    totalSizeKey: total
    itemsKey: result
  ids:
    - adId
    - targetDate
  note:

adScene:
  collName: ad_scene
  description: 多多场景单元列表
  baseType: 2
  path: /venus/api/unit/listPage
  isAnti: true
  isInc: true
  params:
    mallId: 506673970       # 店铺ID
    scenesType: 2           # 场景（多多场景，固定参数）
    beginDate: 2021-05-12   # 指定日期，YYYY-MM-DD
    endDate: 2021-05-12     # 指定日期， YYYY-MM-DD
    pageNumber: 1
    pageSize: 50
  pagination:
    pageNumKey: pageNumber
    pageSizeKey: pageSize
    totalSizeKey: total
    itemsKey: result
  ids:
    - adId
    - targetDate
  note:


